apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-listener
spec:
  selector:
    matchLabels:
      app: cli-listener
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: cli-listener
    spec:
      containers:
      - name: cli-listener
        image: djortiz32/hw3-logger-client

